version: '3'

services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgres:9.4
    networks:
      - back-end
  vote:
    image: voting-app
    ports:
      - "5000:80"
    links:
      - redis  
    networks:
      - back-end
      - front-end  

  result:
    image: result-app
    ports:
      - "5001:80"
    links:
      - db  
    networks:
      - back-end
      - front-end

  worker:
    image: worker-app
    links:
      - redis
      - db
    networks:
      - back-end

networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge
     
volumes:
  redis-data:
  db-data:     